"""
Similar Profiles Report Generator

Generates downloadable reports for peopleAlsoViewed data.
"""
import os
import tempfile
from datetime import datetime
from typing import Dict, Any, List, Optional


def generate_similar_profiles_report(
    profile_name: str,
    profile_title: Optional[str],
    people_also_viewed: List[Dict[str, Any]]
) -> str:
    """
    Generate formatted text report of similar profiles.

    Args:
        profile_name: Name of the main profile
        profile_title: Title/headline of main profile
        people_also_viewed: List of similar profile objects from LinkedIn

    Returns:
        Formatted text report content
    """
    lines = []

    # Header
    lines.append("=" * 70)
    lines.append("SIMILAR PROFILES REPORT")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"Profile: {profile_name}")
    if profile_title:
        lines.append(f"Title: {profile_title}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("=" * 70)
    lines.append("")

    # Count
    count = len(people_also_viewed)
    lines.append(f"Found {count} similar profile{'s' if count != 1 else ''} in {profile_name}'s network:")
    lines.append("")

    # List profiles
    for i, person in enumerate(people_also_viewed, 1):
        # Build full name
        first_name = person.get('first_name', '')
        last_name = person.get('last_name', '')
        full_name = f"{first_name} {last_name}".strip() or person.get('name', 'Unknown')

        lines.append(f"{i}. {full_name}")

        # Add available details
        if person.get('headline'):
            lines.append(f"   {person['headline']}")

        if person.get('public_identifier'):
            linkedin_url = f"https://linkedin.com/in/{person['public_identifier']}"
            lines.append(f"   LinkedIn: {linkedin_url}")
        elif person.get('url'):
            lines.append(f"   LinkedIn: {person['url']}")

        if person.get('follower_count'):
            lines.append(f"   Followers: {person['follower_count']:,}")

        if person.get('premium'):
            lines.append(f"   Premium Member: Yes")

        # Legacy fields (for backward compatibility)
        if person.get('company'):
            lines.append(f"   Company: {person['company']}")

        if person.get('title'):
            lines.append(f"   Title: {person['title']}")

        if person.get('location'):
            lines.append(f"   Location: {person['location']}")

        if person.get('mutualConnections'):
            lines.append(f"   Mutual Connections: {person['mutualConnections']}")

        if person.get('connections'):
            lines.append(f"   Connections: {person['connections']}")

        lines.append("")  # Blank line between profiles

    # Footer
    lines.append("=" * 70)
    lines.append("Generated by AI CRM Extension")
    lines.append("Use this report to identify similar prospects and donors")
    lines.append("=" * 70)

    return "\n".join(lines)


def save_report_to_temp(
    report_content: str,
    profile_name: str
) -> str:
    """
    Save report to temporary file and return file path.

    Args:
        report_content: Text content of report
        profile_name: Name of profile (used in filename)

    Returns:
        Absolute path to saved report file
    """
    # Create safe filename
    safe_name = "".join(c if c.isalnum() or c in [" ", "-", "_"] else "_" for c in profile_name)
    safe_name = safe_name.strip().replace(" ", "_")[:50]  # Limit length

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"similar_profiles_{safe_name}_{timestamp}.txt"

    # Save to temp directory
    temp_dir = tempfile.gettempdir()
    file_path = os.path.join(temp_dir, filename)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    return file_path


def generate_and_save_report(
    profile_name: str,
    profile_title: Optional[str],
    people_also_viewed: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Generate and save similar profiles report.

    Args:
        profile_name: Name of main profile
        profile_title: Title/headline of main profile
        people_also_viewed: List of similar profiles

    Returns:
        Dictionary with report metadata and file path
    """
    # Generate report content
    report_content = generate_similar_profiles_report(
        profile_name,
        profile_title,
        people_also_viewed
    )

    # Save to file
    file_path = save_report_to_temp(report_content, profile_name)

    return {
        "available": True,
        "count": len(people_also_viewed),
        "file_path": file_path,
        "filename": os.path.basename(file_path),
        "content": report_content  # Also include content for inline display
    }
